In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [43]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
features=digits.data
features

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [46]:
targets=digits.target
targets

array([0, 1, 2, ..., 8, 9, 8])

In [47]:
X_train,X_test,y_train,y_test=train_test_split(features,targets,test_size=0.2)

In [48]:
# We are using max_iter=1000 to allow the model more iterations to converge, which can help
#improve performance if the default iteration limit was too low.
logistic_model = LogisticRegression(max_iter=1000)  
logistic_model.fit(X_train, y_train)
logistic_model.score(X_test, y_test)

0.9722222222222222

In [49]:
#Training our same model with SVM(Support Vector Machine)
svm_model=SVC()
svm_model.fit(X_train,y_train)
svm_model.score(X_test,y_test)

0.9833333333333333

In [50]:
#Training the model with Random Forest
random_forest_model=RandomForestClassifier()
random_forest_model.fit(X_train,y_train)
random_forest_model.score(X_test,y_test)

0.9666666666666667

In [51]:
#Now using a K_Fold cross validation to devleop a model

#Basically in K Fold model we split our model in n-section and then for each split
#we train and test data 

from sklearn.model_selection import KFold
kfold_model=KFold(n_splits=3) #n_splits=3 meand m=we are dividing our data into 3 sections
kfold_model

KFold(n_splits=3, random_state=None, shuffle=False)

In [52]:
#Now we are passing or data set 

for train_index,test_index in kfold_model.split([1,2,3,4,5,6,7,8,9]):#we passed 9 dataset
    print(train_index,test_index)
    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [53]:
#We can use this function to train model of different algorithims
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [54]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [55]:
from sklearn.model_selection import cross_val_score

In [ ]:
#using corss_val_score now we are going to evalute score of our different models and decide which model is best for this dataset

In [59]:
#We are using cross_val_score() method to train our model on different split of data set
#cv=3 means dividing aur datasets into 3 folds
cross_val_score(LogisticRegression(max_iter=1000),features,targets,cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [61]:
cross_val_score(SVC(),features,targets,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [62]:
cross_val_score(RandomForestClassifier(),features,targets,cv=3)

array([0.93989983, 0.95158598, 0.93155259])